<?php

use Magento\Framework\View\Element\Template;
use Magento\Vault\Model\Ui\TokenUiComponentProviderInterface;

/** @var Template $block */
$details = $block->getData('details');
$icon = $block->getData('icons')[$details['type']];
$id = $block->escapeHtml($block->getData('id'));
?>
<div data-mage-init='{
        "Pgc_Pgc/js/vault": {
            "container": "payment_<?= /* @noEscape */ $id ?>",
            "publicHash": "<?= $block->escapeHtml($block->getData(TokenUiComponentProviderInterface::COMPONENT_PUBLIC_HASH)); ?>"
        }
    }' id="payment_<?= /* @noEscape */
$id ?>" class="admin__field">
    <div class="admin__field-control control">
        <input type="radio" id="token_switcher_<?= /* @noEscape */
        $id ?>" name="payment[token_switcher]"/>
        <img src="<?= $block->escapeUrl($icon['url']) ?>"
             width="<?= $block->escapeHtml($icon['width']) ?>"
             height="<?= $block->escapeHtml($icon['height']) ?>"
             class="payment-icon">
        <span><?= $block->escapeHtml(__('ending')) ?></span>
        <span><?= $block->escapeHtml($details['maskedCC']) ?></span>
        (<span><?= $block->escapeHtml(__('expires')) ?></span>:
        <span><?= /* @noEscape */ $block->escapeHtml($details['expirationDate']); ?></span>)
    </div>
</div>
